/**
 * Synthetic buyer reviews for PDP demos: **10–25** five-star reviews per catalog product
 * (deterministic count per slug). Each review is one language in `body` only.
 * PDP always shows that text as-is — switching storefront locale does not translate reviews.
 * Deterministic output — safe to re-run on production after `npm run db:migrate`.
 *
 * Safe to re-run: deletes prior seed users with `@reviews.seed.humpbuck` and their reviews.
 * Real buyer reviews (any other user email) are **not** deleted.
 * Run: `npm run db:seed-reviews`
 */
import { randomUUID } from "node:crypto";
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { loadEnvConfig } from "@next/env";
import { prisma } from "../lib/prisma-script";
import { fetchMergedCatalogProducts } from "../lib/catalog-db";
import {
  deterministicReviewCount,
  deterministicReviewDate,
  deterministicReviewerOffset,
  deterministicShuffle,
} from "../lib/review-seed-deterministic";
import { getProductMovement } from "../lib/catalog";
import { REVIEW_SEED_LOCALES, seedReviewBody } from "../lib/review-seed-templates";

loadEnvConfig(process.cwd());
/** Shell/IDE may set DATABASE_URL to localhost; for this script, `.env.local` wins. */
const el = join(process.cwd(), ".env.local");
if (existsSync(el)) {
  for (const line of readFileSync(el, "utf8").split("\n")) {
    const t = line.trim();
    if (!t.startsWith("DATABASE_URL=")) continue;
    let v = t.slice("DATABASE_URL=".length).trim();
    if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'")))
      v = v.slice(1, -1);
    process.env.DATABASE_URL = v;
    break;
  }
}

const SEED_EMAIL_HOST = "reviews.seed.humpbuck";
const REVIEWS_MIN_PER_PRODUCT = 10;
const REVIEWS_MAX_PER_PRODUCT = 25;

type ReviewerProfile = {
  firstName: string;
  lastName: string;
  region: string;
};

/** Diverse English-style names — US, Canada, UK/EU, LatAm, AU/NZ, Asia-Pacific diaspora. */
const REVIEWER_POOL: ReviewerProfile[] = uniqueReviewers([
  { firstName: "Madison", lastName: "Brooks", region: "US" },
  { firstName: "Tyler", lastName: "Reed", region: "US" },
  { firstName: "Olivia", lastName: "Chen", region: "US" },
  { firstName: "Ethan", lastName: "Morales", region: "US" },
  { firstName: "Liam", lastName: "O'Brien", region: "CA" },
  { firstName: "Sophie", lastName: "Laurent", region: "CA" },
  { firstName: "Charlotte", lastName: "Wells", region: "UK" },
  { firstName: "Oliver", lastName: "Hart", region: "UK" },
  { firstName: "Amélie", lastName: "Dupont", region: "FR" },
  { firstName: "Luca", lastName: "Rossi", region: "IT" },
  { firstName: "Hannah", lastName: "Schmidt", region: "DE" },
  { firstName: "Mateo", lastName: "Silva", region: "AR" },
  { firstName: "Valentina", lastName: "Rojas", region: "CL" },
  { firstName: "Bruno", lastName: "Santos", region: "BR" },
  { firstName: "Chloe", lastName: "Nguyen", region: "AU" },
  { firstName: "Jack", lastName: "Mitchell", region: "AU" },
  { firstName: "Priya", lastName: "Sharma", region: "IN" },
  { firstName: "Kenji", lastName: "Tanaka", region: "JP" },
  { firstName: "Mei", lastName: "Lin", region: "TW" },
  { firstName: "Soo-Jin", lastName: "Park", region: "KR" },
  { firstName: "Emma", lastName: "Jansen", region: "NL" },
  { firstName: "Noah", lastName: "Berg", region: "SE" },
  { firstName: "Isabella", lastName: "García", region: "ES" },
  { firstName: "Diego", lastName: "Fernández", region: "MX" },
  { firstName: "Anna", lastName: "Kowalski", region: "PL" },
  { firstName: "Mikhail", lastName: "Petrov", region: "RU" },
  { firstName: "Yasmin", lastName: "Al-Hassan", region: "AE" },
  { firstName: "David", lastName: "Cohen", region: "IL" },
  { firstName: "Rachel", lastName: "Goldstein", region: "US" },
  { firstName: "Marcus", lastName: "Thompson", region: "US" },
  { firstName: "Grace", lastName: "Kim", region: "US" },
  { firstName: "Benjamin", lastName: "Clark", region: "CA" },
  { firstName: "Eleanor", lastName: "Price", region: "UK" },
  { firstName: "James", lastName: "Murphy", region: "IE" },
  { firstName: "Camille", lastName: "Bernard", region: "BE" },
  { firstName: "Felix", lastName: "Weber", region: "AT" },
  { firstName: "Lucia", lastName: "Conti", region: "IT" },
  { firstName: "Tomás", lastName: "Vega", region: "CO" },
  { firstName: "Camila", lastName: "Díaz", region: "PE" },
  { firstName: "Oscar", lastName: "Andersson", region: "SE" },
  { firstName: "Zara", lastName: "Patel", region: "UK" },
  { firstName: "Ryan", lastName: "Walsh", region: "IE" },
  { firstName: "Aisha", lastName: "Mohamed", region: "EG" },
  { firstName: "Daniel", lastName: "Fischer", region: "CH" },
  { firstName: "Nina", lastName: "Horváth", region: "HU" },
  { firstName: "Leo", lastName: "Martinez", region: "US" },
  { firstName: "Harper", lastName: "Singh", region: "CA" },
  { firstName: "William", lastName: "Campbell", region: "NZ" },
  { firstName: "Mia", lastName: "Sato", region: "JP" },
  { firstName: "Alexander", lastName: "Novak", region: "CZ" },
  { firstName: "Elena", lastName: "Popescu", region: "RO" },
  { firstName: "Samuel", lastName: "Okonkwo", region: "NG" },
  { firstName: "Lily", lastName: "Foster", region: "US" },
  { firstName: "Henry", lastName: "Brooks", region: "US" },
  { firstName: "Victoria", lastName: "Romero", region: "ES" },
  { firstName: "Gabriel", lastName: "Lima", region: "BR" },
  { firstName: "Claire", lastName: "Dubois", region: "FR" },
  { firstName: "Nathan", lastName: "Scott", region: "AU" },
  { firstName: "Aria", lastName: "Wong", region: "SG" },
  { firstName: "Jacob", lastName: "Stein", region: "DE" },
  { firstName: "Ruby", lastName: "Taylor", region: "UK" },
  { firstName: "Carlos", lastName: "Herrera", region: "EC" },
  { firstName: "Natalie", lastName: "Volkov", region: "UA" },
  { firstName: "Andrew", lastName: "Pearson", region: "CA" },
  { firstName: "Sienna", lastName: "Hayes", region: "AU" },
  { firstName: "Mohammed", lastName: "Rahman", region: "UK" },
  { firstName: "Julia", lastName: "Nowak", region: "PL" },
  { firstName: "Chris", lastName: "Hamilton", region: "US" },
  { firstName: "Paige", lastName: "Sullivan", region: "US" },
  { firstName: "Max", lastName: "Keller", region: "DE" },
  { firstName: "Inés", lastName: "Morales", region: "ES" },
  { firstName: "Theo", lastName: "Beaumont", region: "FR" },
  { firstName: "Hana", lastName: "Yamamoto", region: "JP" },
  { firstName: "Sean", lastName: "McCarthy", region: "IE" },
  { firstName: "Alina", lastName: "Popov", region: "MD" },
  { firstName: "Jordan", lastName: "Ellis", region: "US" },
  { firstName: "Freya", lastName: "Nielsen", region: "DK" },
  { firstName: "Rafael", lastName: "Costa", region: "PT" },
  { firstName: "Keiko", lastName: "Ito", region: "JP" },
  { firstName: "Simon", lastName: "Fraser", region: "CA" },
  { firstName: "Tessa", lastName: "van Dijk", region: "NL" },
  { firstName: "Marco", lastName: "Esposito", region: "IT" },
  { firstName: "Anya", lastName: "Ivanova", region: "RU" },
  { firstName: "Luke", lastName: "Bennett", region: "UK" },
  { firstName: "Sara", lastName: "Ahmed", region: "CA" },
  { firstName: "Dylan", lastName: "Rivera", region: "US" },
  { firstName: "Imogen", lastName: "Clarke", region: "AU" },
  { firstName: "André", lastName: "Carvalho", region: "BR" },
  { firstName: "Yuki", lastName: "Nakamura", region: "JP" },
  { firstName: "Hugo", lastName: "Leroy", region: "FR" },
  { firstName: "Petra", lastName: "Horváth", region: "HU" },
  { firstName: "Finn", lastName: "Olsen", region: "NO" },
  { firstName: "Layla", lastName: "Hassan", region: "US" },
  { firstName: "George", lastName: "Papadopoulos", region: "GR" },
  { firstName: "Zoe", lastName: "Adams", region: "US" },
  { firstName: "Antoine", lastName: "Moreau", region: "FR" },
  { firstName: "Min-Jun", lastName: "Lee", region: "KR" },
  { firstName: "Bethany", lastName: "Cole", region: "UK" },
  { firstName: "Ravi", lastName: "Kapoor", region: "IN" },
  { firstName: "Stella", lastName: "Müller", region: "DE" },
  { firstName: "Pedro", lastName: "Almeida", region: "PT" },
  { firstName: "Wendy", lastName: "Chang", region: "TW" },
  { firstName: "Colin", lastName: "MacLeod", region: "UK" },
  { firstName: "Nadia", lastName: "Khan", region: "PK" },
  { firstName: "Eric", lastName: "Johansson", region: "SE" },
  { firstName: "Maya", lastName: "Desai", region: "CA" },
  { firstName: "Trevor", lastName: "Ngata", region: "NZ" },
  { firstName: "Helena", lastName: "Kovács", region: "HU" },
  { firstName: "Jonah", lastName: "Weiss", region: "US" },
  { firstName: "Carmen", lastName: "Ruiz", region: "ES" },
  { firstName: "Philip", lastName: "Schneider", region: "DE" },
  { firstName: "Aiden", lastName: "Walsh", region: "IE" },
  { firstName: "Bianca", lastName: "Romano", region: "IT" },
  { firstName: "Tariq", lastName: "Malik", region: "UK" },
  { firstName: "Vanessa", lastName: "Torres", region: "US" },
  { firstName: "Gavin", lastName: "Stewart", region: "CA" },
  { firstName: "Elise", lastName: "Mercier", region: "BE" },
  { firstName: "Ronan", lastName: "Kelly", region: "IE" },
  { firstName: "Jasmine", lastName: "Ho", region: "HK" },
  { firstName: "Victor", lastName: "Sousa", region: "BR" },
  { firstName: "Penelope", lastName: "Grant", region: "AU" },
  { firstName: "Adrian", lastName: "Wolff", region: "DE" },
  { firstName: "Naomi", lastName: "Levi", region: "IL" },
  { firstName: "Caleb", lastName: "Owens", region: "US" },
  { firstName: "Florence", lastName: "King", region: "UK" },
  { firstName: "Rodrigo", lastName: "Pereira", region: "PT" },
  { firstName: "Akira", lastName: "Watanabe", region: "JP" },
  { firstName: "Morgan", lastName: "Price", region: "US" },
  { firstName: "Isabelle", lastName: "Girard", region: "CA" },
  { firstName: "Darius", lastName: "Ionescu", region: "RO" },
  { firstName: "Talia", lastName: "Ben-David", region: "IL" },
  { firstName: "Oscar", lastName: "Lindström", region: "SE" },
  { firstName: "Renee", lastName: "Baker", region: "US" },
  { firstName: "Hassan", lastName: "Farouk", region: "EG" },
  { firstName: "Claudia", lastName: "Mendoza", region: "MX" },
  { firstName: "Ian", lastName: "Robertson", region: "UK" },
  { firstName: "Suki", lastName: "Choi", region: "KR" },
  { firstName: "Dominic", lastName: "Russo", region: "IT" },
  { firstName: "Alana", lastName: "Ferguson", region: "NZ" },
  { firstName: "Pierre", lastName: "Fontaine", region: "FR" },
  { firstName: "Katie", lastName: "Dunn", region: "US" },
  { firstName: "Raj", lastName: "Mehta", region: "IN" },
  { firstName: "Eva", lastName: "Bakker", region: "NL" },
  { firstName: "Connor", lastName: "Flynn", region: "IE" },
  { firstName: "Lucía", lastName: "Ortega", region: "ES" },
  { firstName: "Micah", lastName: "Steinberg", region: "US" },
  { firstName: "Yara", lastName: "Saleh", region: "JO" },
  { firstName: "Blake", lastName: "Harper", region: "CA" },
  { firstName: "Greta", lastName: "Fuchs", region: "AT" },
  { firstName: "Malik", lastName: "Johnson", region: "US" },
  { firstName: "Serena", lastName: "Lombardi", region: "IT" },
  { firstName: "Tobias", lastName: "Krüger", region: "DE" },
  { firstName: "Amira", lastName: "Zayed", region: "AE" },
  { firstName: "Declan", lastName: "Murphy", region: "IE" },
  { firstName: "Holly", lastName: "Parker", region: "AU" },
  { firstName: "Enzo", lastName: "Bianchi", region: "IT" },
  { firstName: "Nora", lastName: "Eriksson", region: "SE" },
  { firstName: "Brandon", lastName: "Hayes", region: "US" },
  { firstName: "Simone", lastName: "Duarte", region: "BR" },
  { firstName: "Eliza", lastName: "Monroe", region: "US" },
  { firstName: "Kai", lastName: "Andersen", region: "DK" },
  { firstName: "Fatima", lastName: "Ouazzani", region: "MA" },
  { firstName: "Spencer", lastName: "Quinn", region: "CA" },
  { firstName: "Miriam", lastName: "Goldberg", region: "US" },
  { firstName: "Leandro", lastName: "Gomes", region: "BR" },
  { firstName: "Tanya", lastName: "Petrova", region: "BG" },
  { firstName: "Wesley", lastName: "Armstrong", region: "US" },
  { firstName: "Ingrid", lastName: "Holm", region: "NO" },
  { firstName: "João", lastName: "Ferreira", region: "PT" },
  { firstName: "Sabrina", lastName: "Ali", region: "UK" },
  { firstName: "Elliot", lastName: "Marsh", region: "US" },
  { firstName: "Chiara", lastName: "Marchetti", region: "IT" },
  { firstName: "Devon", lastName: "Sinclair", region: "CA" },
  { firstName: "Anika", lastName: "Reddy", region: "IN" },
  { firstName: "Tristan", lastName: "Becker", region: "DE" },
  { firstName: "Rosie", lastName: "McLean", region: "UK" },
  { firstName: "Felipe", lastName: "Castro", region: "CL" },
  { firstName: "Genevieve", lastName: "Tremblay", region: "CA" },
  { firstName: "Owen", lastName: "Dalton", region: "AU" },
  { firstName: "Leila", lastName: "Karimi", region: "IR" },
  { firstName: "Marshall", lastName: "Cruz", region: "US" },
  { firstName: "Saskia", lastName: "de Vries", region: "NL" },
  { firstName: "Ruben", lastName: "Navarro", region: "ES" },
  { firstName: "Hope", lastName: "Whitman", region: "US" },
  { firstName: "Nikolai", lastName: "Volkov", region: "RU" },
  { firstName: "Celeste", lastName: "Marin", region: "FR" },
  { firstName: "Asher", lastName: "Bloom", region: "US" },
  { firstName: "Mariana", lastName: "Lopes", region: "BR" },
  { firstName: "Callum", lastName: "Reid", region: "UK" },
  { firstName: "Denise", lastName: "Kramer", region: "DE" },
  { firstName: "Javier", lastName: "Mendez", region: "MX" },
  { firstName: "Tara", lastName: "O'Sullivan", region: "IE" },
  { firstName: "Hiro", lastName: "Suzuki", region: "JP" },
  { firstName: "Brooke", lastName: "Sinclair", region: "AU" },
  { firstName: "Emilio", lastName: "Ramos", region: "ES" },
  { firstName: "Vera", lastName: "Smirnova", region: "RU" },
  { firstName: "Quinn", lastName: "Ashford", region: "US" },
  { firstName: "Linnea", lastName: "Bergström", region: "SE" },
  { firstName: "Rohan", lastName: "Das", region: "IN" },
  { firstName: "Paola", lastName: "Ricci", region: "IT" },
  { firstName: "Grant", lastName: "Henderson", region: "CA" },
  { firstName: "Yvonne", lastName: "Ng", region: "SG" },
  { firstName: "Silas", lastName: "Koenig", region: "DE" },
  { firstName: "Monica", lastName: "Vargas", region: "CO" },
  { firstName: "Reed", lastName: "Palmer", region: "US" },
  { firstName: "Anouk", lastName: "Vermeulen", region: "BE" },
  { firstName: "Mateusz", lastName: "Wojcik", region: "PL" },
  { firstName: "Cassidy", lastName: "Brooks", region: "US" },
  { firstName: "Rosa", lastName: "Delgado", region: "ES" },
  { firstName: "Tomasz", lastName: "Kaminski", region: "PL" },
  { firstName: "Skylar", lastName: "Jennings", region: "US" },
  { firstName: "Amara", lastName: "Okafor", region: "NG" },
  { firstName: "Lars", lastName: "Hansen", region: "DK" },
  { firstName: "Veronica", lastName: "Santana", region: "US" },
  { firstName: "Idris", lastName: "Camara", region: "FR" },
  { firstName: "Heidi", lastName: "Zimmermann", region: "CH" },
  { firstName: "Clayton", lastName: "Vance", region: "US" },
  { firstName: "Paloma", lastName: "Iglesias", region: "ES" },
  { firstName: "Stefan", lastName: "Dragomir", region: "RO" },
  { firstName: "Jade", lastName: "Prescott", region: "AU" },
  { firstName: "Mohamed", lastName: "El-Sayed", region: "EG" },
  { firstName: "Brittany", lastName: "Coleman", region: "US" },
  { firstName: "Henrik", lastName: "Lund", region: "NO" },
  { firstName: "Solange", lastName: "Martins", region: "PT" },
  { firstName: "Kieran", lastName: "Boyd", region: "IE" },
  { firstName: "Ayumi", lastName: "Kobayashi", region: "JP" },
  { firstName: "Derek", lastName: "Finch", region: "UK" },
  { firstName: "Luna", lastName: "Reyes", region: "PH" },
  { firstName: "Arjun", lastName: "Nair", region: "IN" },
  { firstName: "Colette", lastName: "Renard", region: "FR" },
  { firstName: "Tucker", lastName: "Mason", region: "US" },
  { firstName: "Esme", lastName: "Walters", region: "UK" },
  { firstName: "Ricardo", lastName: "Valdez", region: "MX" },
  { firstName: "Nell", lastName: "Fitzgerald", region: "IE" },
  { firstName: "Sven", lastName: "Larsson", region: "SE" },
  { firstName: "Danica", lastName: "Popovic", region: "RS" },
  { firstName: "Warren", lastName: "Holt", region: "US" },
  { firstName: "Giulia", lastName: "Ferrari", region: "IT" },
  { firstName: "Beau", lastName: "Thomson", region: "AU" },
  { firstName: "Hilda", lastName: "Szabó", region: "HU" },
  { firstName: "Malcolm", lastName: "Ingram", region: "CA" },
  { firstName: "Keira", lastName: "Donovan", region: "IE" },
  { firstName: "Andres", lastName: "Guerrero", region: "EC" },
  { firstName: "Phoebe", lastName: "Lang", region: "DE" },
  { firstName: "Zachary", lastName: "Pope", region: "US" },
  { firstName: "Renata", lastName: "Souza", region: "BR" },
  { firstName: "Gideon", lastName: "Shapiro", region: "US" },
  { firstName: "Marta", lastName: "Kowalczyk", region: "PL" },
  { firstName: "Ellis", lastName: "Cartwright", region: "UK" },
  { firstName: "Noemi", lastName: "Paredes", region: "PE" },
  { firstName: "Frank", lastName: "Dubois", region: "CA" },
  { firstName: "Soraya", lastName: "Benali", region: "FR" },
  { firstName: "Holden", lastName: "Crane", region: "US" },
  { firstName: "Petra", lastName: "Novak", region: "CZ" },
  { firstName: "Joon", lastName: "Han", region: "KR" },
  { firstName: "Margot", lastName: "Leclerc", region: "FR" },
  { firstName: "Curtis", lastName: "Baldwin", region: "US" },
  { firstName: "Anastasia", lastName: "Morozova", region: "RU" },
  { firstName: "Rory", lastName: "Gallagher", region: "IE" },
  { firstName: "Selena", lastName: "Cruz", region: "US" },
  { firstName: "Niklas", lastName: "Brandt", region: "DE" },
  { firstName: "Alba", lastName: "Romero", region: "ES" },
  { firstName: "Trent", lastName: "Holbrook", region: "US" },
  { firstName: "Mireille", lastName: "Bonnet", region: "FR" },
  { firstName: "Sanjay", lastName: "Gupta", region: "IN" },
  { firstName: "Willa", lastName: "Crawford", region: "AU" },
  { firstName: "Emil", lastName: "Petersen", region: "DK" },
  { firstName: "Catalina", lastName: "Muñoz", region: "CL" },
  { firstName: "Garrett", lastName: "Simmons", region: "US" },
  { firstName: "Ines", lastName: "Alves", region: "PT" },
  { firstName: "Yosef", lastName: "Avraham", region: "IL" },
  { firstName: "Piper", lastName: "Dalton", region: "US" },
  { firstName: "Fabian", lastName: "Richter", region: "DE" },
  { firstName: "Laila", lastName: "Mansour", region: "LB" },
  { firstName: "Colton", lastName: "Reeves", region: "US" },
  { firstName: "Odette", lastName: "Marchand", region: "FR" },
  { firstName: "Haruki", lastName: "Mori", region: "JP" },
  { firstName: "Brianna", lastName: "Santos", region: "US" },
  { firstName: "Gregor", lastName: "Huber", region: "AT" },
  { firstName: "Tamara", lastName: "Jovanovic", region: "RS" },
  { firstName: "Lincoln", lastName: "Archer", region: "AU" },
  { firstName: "Nia", lastName: "Williams", region: "US" },
  { firstName: "Basil", lastName: "Khoury", region: "LB" },
  { firstName: "Ophelia", lastName: "Stone", region: "UK" },
  { firstName: "Rafael", lastName: "Mendes", region: "PT" },
  { firstName: "Shelby", lastName: "Griffin", region: "US" },
  { firstName: "Maren", lastName: "Solberg", region: "NO" },
  { firstName: "Diego", lastName: "Acosta", region: "UY" },
  { firstName: "Tessa", lastName: "Ramirez", region: "US" },
  { firstName: "Viktor", lastName: "Orlov", region: "RU" },
  { firstName: "Camille", lastName: "Drouin", region: "FR" },
  { firstName: "Jonah", lastName: "Peters", region: "CA" },
  { firstName: "Meera", lastName: "Iyer", region: "IN" },
  { firstName: "Sterling", lastName: "Hayward", region: "US" },
  { firstName: "Franziska", lastName: "Bauer", region: "DE" },
  { firstName: "Luciano", lastName: "Barbosa", region: "BR" },
  { firstName: "Whitney", lastName: "Dunn", region: "US" },
  { firstName: "Ewan", lastName: "MacDonald", region: "UK" },
  { firstName: "Paloma", lastName: "Vega", region: "MX" },
  { firstName: "Soren", lastName: "Christensen", region: "DK" },
  { firstName: "Ayla", lastName: "Demir", region: "TR" },
  { firstName: "Marshall", lastName: "Keating", region: "US" },
  { firstName: "Isla", lastName: "Fraser", region: "CA" },
  { firstName: "Renzo", lastName: "Galli", region: "IT" },
  { firstName: "Kendra", lastName: "Shaw", region: "US" },
  { firstName: "Pavel", lastName: "Sokolov", region: "RU" },
  { firstName: "Amelie", lastName: "Fournier", region: "FR" },
  { firstName: "Toby", lastName: "Wright", region: "AU" },
  { firstName: "Shreya", lastName: "Banerjee", region: "IN" },
  { firstName: "Landon", lastName: "Cross", region: "US" },
  { firstName: "Helene", lastName: "Maier", region: "DE" },
  { firstName: "Ignacio", lastName: "Ponce", region: "AR" },
  { firstName: "Jocelyn", lastName: "Tate", region: "US" },
  { firstName: "Matteo", lastName: "Colombo", region: "IT" },
  { firstName: "Rowan", lastName: "Fitzpatrick", region: "IE" },
  { firstName: "Sana", lastName: "Qureshi", region: "PK" },
  { firstName: "Beckett", lastName: "Lawson", region: "US" },
  { firstName: "Giselle", lastName: "Morel", region: "FR" },
  { firstName: "Hector", lastName: "Salazar", region: "MX" },
  { firstName: "Alison", lastName: "Beatty", region: "CA" },
  { firstName: "Riku", lastName: "Aoki", region: "JP" },
  { firstName: "Delilah", lastName: "Monroe", region: "US" },
  { firstName: "Stijn", lastName: "Bakker", region: "NL" },
  { firstName: "Corinne", lastName: "Perrin", region: "CH" },
  { firstName: "Angelo", lastName: "Vitale", region: "IT" },
  { firstName: "Hayley", lastName: "Burton", region: "UK" },
  { firstName: "Dmitri", lastName: "Kuznetsov", region: "RU" },
  { firstName: "Fallon", lastName: "Reyes", region: "US" },
  { firstName: "Elodie", lastName: "Chevalier", region: "FR" },
  { firstName: "Tanner", lastName: "McBride", region: "US" },
  { firstName: "Bianca", lastName: "Ionescu", region: "RO" },
  { firstName: "Kian", lastName: "O'Connor", region: "IE" },
  { firstName: "Yuna", lastName: "Seo", region: "KR" },
  { firstName: "Preston", lastName: "Hale", region: "US" },
  { firstName: "Marisol", lastName: "Aguilar", region: "ES" },
  { firstName: "Ulrich", lastName: "Neumann", region: "DE" },
  { firstName: "Tiana", lastName: "Brooks", region: "US" },
  { firstName: "Gustavo", lastName: "Nascimento", region: "BR" },
  { firstName: "Fiona", lastName: "McKay", region: "UK" },
  { firstName: "Arlo", lastName: "Whitmore", region: "US" },
  { firstName: "Constanza", lastName: "Riquelme", region: "CL" },
  { firstName: "Nolan", lastName: "Greer", region: "CA" },
  { firstName: "Svetlana", lastName: "Belova", region: "RU" },
  { firstName: "Remy", lastName: "Dubois", region: "FR" },
  { firstName: "Jasper", lastName: "Collins", region: "AU" },
  { firstName: "Anahi", lastName: "Luna", region: "MX" },
  { firstName: "Cedric", lastName: "Thompson", region: "US" },
  { firstName: "Lin", lastName: "Zhao", region: "CN" },
  { firstName: "Maeve", lastName: "Sullivan", region: "IE" },
  { firstName: "Thiago", lastName: "Oliveira", region: "BR" },
  { firstName: "Vivian", lastName: "Cho", region: "US" },
  { firstName: "Oleg", lastName: "Morozov", region: "RU" },
  { firstName: "Celine", lastName: "Rousseau", region: "FR" },
  { firstName: "Darren", lastName: "Whitfield", region: "US" },
  { firstName: "Ingrid", lastName: "Larsen", region: "NO" },
  { firstName: "Emmanuel", lastName: "Nkosi", region: "ZA" },
  { firstName: "Sadie", lastName: "Holland", region: "US" },
  { firstName: "Rafaela", lastName: "Campos", region: "BR" },
  { firstName: "Conor", lastName: "Doyle", region: "IE" },
  { firstName: "Minh", lastName: "Tran", region: "VN" },
  { firstName: "Bryce", lastName: "Langford", region: "US" },
  { firstName: "Helena", lastName: "Costa", region: "PT" },
  { firstName: "Zain", lastName: "Abbasi", region: "PK" },
  { firstName: "Georgia", lastName: "Porter", region: "AU" },
  { firstName: "Felix", lastName: "Arnold", region: "DE" },
  { firstName: "Marina", lastName: "Klein", region: "US" },
  { firstName: "Tomas", lastName: "Jankovic", region: "SK" },
  { firstName: "Avery", lastName: "Sinclair", region: "CA" },
  { firstName: "Lea", lastName: "Hoffmann", region: "DE" },
  { firstName: "Rodney", lastName: "Fisher", region: "US" },
  { firstName: "Paloma", lastName: "Serrano", region: "ES" },
  { firstName: "Nikita", lastName: "Sergeev", region: "RU" },
  { firstName: "Cora", lastName: "Bennett", region: "US" },
  { firstName: "Enrique", lastName: "Villanueva", region: "ES" },
  { firstName: "Sasha", lastName: "Petrovic", region: "RS" },
  { firstName: "Miles", lastName: "Donnelly", region: "US" },
  { firstName: "Noor", lastName: "Haddad", region: "JO" },
  { firstName: "Graham", lastName: "Steele", region: "CA" },
  { firstName: "Elina", lastName: "Kalnina", region: "LV" },
  { firstName: "Trevor", lastName: "Nash", region: "US" },
  { firstName: "Bianca", lastName: "Mancini", region: "IT" },
  { firstName: "Hugo", lastName: "Silveira", region: "BR" },
  { firstName: "Janet", lastName: "Cunningham", region: "US" },
  { firstName: "Levi", lastName: "Rosenberg", region: "US" },
  { firstName: "Camila", lastName: "Restrepo", region: "CO" },
  { firstName: "Orion", lastName: "Blake", region: "US" },
  { firstName: "Freja", lastName: "Sørensen", region: "DK" },
  { firstName: "Antonio", lastName: "Marques", region: "PT" },
  { firstName: "Lena", lastName: "Fischer", region: "DE" },
  { firstName: "Rhys", lastName: "Evans", region: "UK" },
  { firstName: "Yasmeen", lastName: "Karim", region: "US" },
  { firstName: "Pablo", lastName: "Iglesias", region: "ES" },
  { firstName: "Shane", lastName: "McGregor", region: "CA" },
  { firstName: "Nellie", lastName: "Ortiz", region: "US" },
  { firstName: "Vladimir", lastName: "Ivanov", region: "RU" },
  { firstName: "Colette", lastName: "Bernier", region: "CA" },
  { firstName: "Jaden", lastName: "Morris", region: "US" },
  { firstName: "Anika", lastName: "Schwarz", region: "DE" },
  { firstName: "Rafael", lastName: "Quintana", region: "MX" },
  { firstName: "Tessa", lastName: "Monroe", region: "US" },
  { firstName: "Finnian", lastName: "Walsh", region: "IE" },
  { firstName: "Lucia", lastName: "Herrera", region: "ES" },
  { firstName: "Brooks", lastName: "Henley", region: "US" },
  { firstName: "Katya", lastName: "Volkova", region: "RU" },
  { firstName: "Ellis", lastName: "Mercier", region: "FR" },
  { firstName: "Tamara", lastName: "Singh", region: "CA" },
  { firstName: "Clay", lastName: "Rodgers", region: "US" },
  { firstName: "Ines", lastName: "Carvalho", region: "PT" },
  { firstName: "Sawyer", lastName: "Pittman", region: "US" },
  { firstName: "Marta", lastName: "Gonzalez", region: "ES" },
  { firstName: "Nikolai", lastName: "Dobrev", region: "BG" },
  { firstName: "Renee", lastName: "Abbott", region: "US" },
  { firstName: "Giorgio", lastName: "Moretti", region: "IT" },
  { firstName: "Holly", lastName: "Jennings", region: "UK" },
  { firstName: "Andre", lastName: "Silva", region: "BR" },
  { firstName: "Paige", lastName: "Donovan", region: "US" },
  { firstName: "Stella", lastName: "Nguyen", region: "AU" },
  { firstName: "Emiliano", lastName: "Rivas", region: "AR" },
  { firstName: "Beth", lastName: "Caldwell", region: "US" },
  { firstName: "Henri", lastName: "Lemoine", region: "FR" },
  { firstName: "Kyle", lastName: "Ramsey", region: "US" },
  { firstName: "Anya", lastName: "Petrova", region: "BG" },
  { firstName: "Declan", lastName: "Frost", region: "CA" },
  { firstName: "Marlene", lastName: "Krause", region: "DE" },
  { firstName: "Troy", lastName: "Benson", region: "US" },
  { firstName: "Isabel", lastName: "Castro", region: "ES" },
  { firstName: "Ravi", lastName: "Malhotra", region: "IN" },
  { firstName: "Wren", lastName: "Ashley", region: "US" },
  { firstName: "Luc", lastName: "Fontaine", region: "FR" },
  { firstName: "Harper", lastName: "McMillan", region: "CA" },
  { firstName: "Diego", lastName: "Salinas", region: "CL" },
  { firstName: "Alana", lastName: "Whitaker", region: "US" },
  { firstName: "Stefan", lastName: "Meyer", region: "DE" },
  { firstName: "Nadia", lastName: "Rossi", region: "IT" },
  { firstName: "Grant", lastName: "Ellison", region: "US" },
  { firstName: "Yuki", lastName: "Hayashi", region: "JP" },
  { firstName: "Monique", lastName: "Duval", region: "FR" },
  { firstName: "Carter", lastName: "Hughes", region: "US" },
  { firstName: "Elena", lastName: "Markovic", region: "RS" },
  { firstName: "Ruben", lastName: "Alvarez", region: "ES" },
  { firstName: "Talia", lastName: "Goldman", region: "US" },
  { firstName: "Oskar", lastName: "Lindqvist", region: "SE" },
  { firstName: "Camille", lastName: "Roy", region: "CA" },
  { firstName: "Jonah", lastName: "Steiner", region: "US" },
  { firstName: "Bianca", lastName: "Flores", region: "MX" },
  { firstName: "Malachi", lastName: "Brooks", region: "US" },
  { firstName: "Freya", lastName: "Olsen", region: "NO" },
  { firstName: "Lucas", lastName: "Pereira", region: "BR" },
  { firstName: "Simone", lastName: "Becker", region: "DE" },
  { firstName: "Riley", lastName: "Chambers", region: "US" },
  { firstName: "Paloma", lastName: "Navarro", region: "ES" },
  { firstName: "Ethan", lastName: "Kaur", region: "CA" },
  { firstName: "Mira", lastName: "Johansson", region: "SE" },
  { firstName: "Dante", lastName: "Romano", region: "IT" },
  { firstName: "Shelley", lastName: "Pratt", region: "US" },
  { firstName: "Arman", lastName: "Suleymanov", region: "AZ" },
  { firstName: "Clara", lastName: "Hoffman", region: "DE" },
  { firstName: "Jesse", lastName: "Matthews", region: "US" },
  { firstName: "Valeria", lastName: "Soto", region: "CL" },
  { firstName: "Niall", lastName: "Burke", region: "IE" },
  { firstName: "Keira", lastName: "Walsh", region: "UK" },
  { firstName: "Marco", lastName: "Delgado", region: "MX" },
  { firstName: "Audrey", lastName: "Sinclair", region: "US" },
  { firstName: "Henrik", lastName: "Ahlström", region: "SE" },
  { firstName: "Luz", lastName: "Medina", region: "PE" },
  { firstName: "Toby", lastName: "Franklin", region: "US" },
  { firstName: "Anastasia", lastName: "Kuzmina", region: "RU" },
  { firstName: "Gavin", lastName: "O'Malley", region: "IE" },
  { firstName: "Selina", lastName: "Weber", region: "DE" },
  { firstName: "Rodney", lastName: "Vasquez", region: "US" },
  { firstName: "Ines", lastName: "Lopez", region: "ES" },
  { firstName: "Callan", lastName: "Reid", region: "AU" },
  { firstName: "Maya", lastName: "Bennett", region: "US" },
  { firstName: "Felipe", lastName: "Torres", region: "BR" },
  { firstName: "Gretchen", lastName: "Schulz", region: "DE" },
  { firstName: "Leo", lastName: "Martinez", region: "US" },
  { firstName: "Soraya", lastName: "Ndiaye", region: "SN" },
  { firstName: "Warren", lastName: "Cole", region: "CA" },
  { firstName: "Eliza", lastName: "Parker", region: "US" },
  { firstName: "Tomás", lastName: "Ribeiro", region: "PT" },
  { firstName: "Nina", lastName: "Keller", region: "CH" },
  { firstName: "Blake", lastName: "Harrington", region: "US" },
  { firstName: "Chiara", lastName: "Bellini", region: "IT" },
  { firstName: "Rohan", lastName: "Chatterjee", region: "IN" },
  { firstName: "Paola", lastName: "Mendez", region: "MX" },
  { firstName: "Elliot", lastName: "Graves", region: "US" },
  { firstName: "Helene", lastName: "Schmitt", region: "FR" },
  { firstName: "Connor", lastName: "Bishop", region: "UK" },
  { firstName: "Amira", lastName: "Farah", region: "US" },
  { firstName: "Stefano", lastName: "Rizzo", region: "IT" },
  { firstName: "Jade", lastName: "Montgomery", region: "AU" },
  { firstName: "Trevor", lastName: "Lang", region: "US" },
  { firstName: "Noemi", lastName: "Varga", region: "HU" },
  { firstName: "Ruben", lastName: "Castillo", region: "ES" },
  { firstName: "Skye", lastName: "Anderson", region: "US" },
  { firstName: "Matias", lastName: "Sepulveda", region: "CL" },
  { firstName: "Genevieve", lastName: "Roy", region: "CA" },
  { firstName: "Hassan", lastName: "Ibrahim", region: "EG" },
  { firstName: "Penny", lastName: "Walters", region: "UK" },
  { firstName: "Diego", lastName: "Morales", region: "CO" },
  { firstName: "Alison", lastName: "Hayes", region: "US" },
  { firstName: "Renata", lastName: "Silva", region: "BR" },
  { firstName: "Cormac", lastName: "Flynn", region: "IE" },
  { firstName: "Yvonne", lastName: "Leung", region: "HK" },
  { firstName: "Marshall", lastName: "Keene", region: "US" },
  { firstName: "Ingrid", lastName: "Holm", region: "SE" },
  { firstName: "Luca", lastName: "Marini", region: "IT" },
  { firstName: "Tiana", lastName: "Brooks", region: "US" },
  { firstName: "Pavel", lastName: "Horak", region: "CZ" },
  { firstName: "Serena", lastName: "Cole", region: "US" },
  { firstName: "Antoine", lastName: "Lambert", region: "FR" },
  { firstName: "Keith", lastName: "Sanders", region: "US" },
  { firstName: "Marta", lastName: "Nowak", region: "PL" },
  { firstName: "Felix", lastName: "Brandt", region: "DE" },
  { firstName: "Ruby", lastName: "Stevens", region: "AU" },
  { firstName: "Emilio", lastName: "Cruz", region: "MX" },
  { firstName: "Nell", lastName: "Prescott", region: "US" },
  { firstName: "Sven", lastName: "Eriksson", region: "SE" },
  { firstName: "Camila", lastName: "Ferreira", region: "BR" },
  { firstName: "Darren", lastName: "Whitfield", region: "US" },
  { firstName: "Elodie", lastName: "Martin", region: "FR" },
  { firstName: "Jonah", lastName: "Stein", region: "US" },
  { firstName: "Anouk", lastName: "Visser", region: "NL" },
  { firstName: "Rafael", lastName: "Ochoa", region: "MX" },
  { firstName: "Hope", lastName: "Sinclair", region: "CA" },
  { firstName: "Niklas", lastName: "Bergman", region: "SE" },
  { firstName: "Mariana", lastName: "Luna", region: "US" },
  { firstName: "Henrik", lastName: "Aalto", region: "FI" },
  { firstName: "Tessa", lastName: "Monroe", region: "US" },
  { firstName: "Giulia", lastName: "Romano", region: "IT" },
  { firstName: "Warren", lastName: "Holt", region: "US" },
  { firstName: "Leila", lastName: "Karimi", region: "US" },
  { firstName: "Oscar", lastName: "Lindström", region: "SE" },
  { firstName: "Bianca", lastName: "Mancini", region: "IT" },
  { firstName: "Clayton", lastName: "Vance", region: "US" },
  { firstName: "Freya", lastName: "Nielsen", region: "DK" },
  { firstName: "Rodrigo", lastName: "Pereira", region: "PT" },
  { firstName: "Shelby", lastName: "Griffin", region: "US" },
  { firstName: "Yuki", lastName: "Hayashi", region: "JP" },
  { firstName: "Marcus", lastName: "Thompson", region: "US" },
  { firstName: "Elena", lastName: "Popescu", region: "RO" },
  { firstName: "Grant", lastName: "Henderson", region: "CA" },
  { firstName: "Paloma", lastName: "Vega", region: "MX" },
  { firstName: "Derek", lastName: "Finch", region: "UK" },
  { firstName: "Min-Jun", lastName: "Lee", region: "KR" },
  { firstName: "Vanessa", lastName: "Torres", region: "US" },
  { firstName: "Luca", lastName: "Rossi", region: "IT" },
  { firstName: "Chloe", lastName: "Nguyen", region: "AU" },
  { firstName: "Tyler", lastName: "Reed", region: "US" },
  { firstName: "Amélie", lastName: "Dupont", region: "FR" },
  { firstName: "Kenji", lastName: "Tanaka", region: "JP" },
  { firstName: "Sophie", lastName: "Laurent", region: "CA" },
  { firstName: "Mateo", lastName: "Silva", region: "AR" },
  { firstName: "Charlotte", lastName: "Wells", region: "UK" },
  { firstName: "Priya", lastName: "Sharma", region: "IN" },
  { firstName: "Liam", lastName: "O'Brien", region: "CA" },
  { firstName: "Hannah", lastName: "Schmidt", region: "DE" },
  { firstName: "Valentina", lastName: "Rojas", region: "CL" },
  { firstName: "Jack", lastName: "Mitchell", region: "AU" },
  { firstName: "Olivia", lastName: "Chen", region: "US" },
  { firstName: "Bruno", lastName: "Santos", region: "BR" },
  { firstName: "Emma", lastName: "Jansen", region: "NL" },
  { firstName: "Diego", lastName: "Fernández", region: "MX" },
  { firstName: "Anna", lastName: "Kowalski", region: "PL" },
  { firstName: "Mikhail", lastName: "Petrov", region: "RU" },
  { firstName: "Yasmin", lastName: "Al-Hassan", region: "AE" },
  { firstName: "David", lastName: "Cohen", region: "IL" },
  { firstName: "Madison", lastName: "Brooks", region: "US" },
  { firstName: "Oliver", lastName: "Hart", region: "UK" },
  { firstName: "Mei", lastName: "Lin", region: "TW" },
  { firstName: "Soo-Jin", lastName: "Park", region: "KR" },
  { firstName: "Noah", lastName: "Berg", region: "SE" },
  { firstName: "Isabella", lastName: "García", region: "ES" },
  { firstName: "Ethan", lastName: "Morales", region: "US" },
]);

function uniqueReviewers(profiles: ReviewerProfile[]): ReviewerProfile[] {
  const seen = new Set<string>();
  const out: ReviewerProfile[] = [];
  for (const p of profiles) {
    const key = `${p.firstName}|${p.lastName}`;
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(p);
  }
  return out;
}

function displayName(p: ReviewerProfile): string {
  return `${p.firstName} ${p.lastName[0]}.`;
}

async function main() {
  const deleted = await prisma.user.deleteMany({
    where: { email: { endsWith: `@${SEED_EMAIL_HOST}` } },
  });
  console.log(`Removed ${deleted.count} prior seed reviewer account(s) (reviews cascade).`);

  const catalog = await fetchMergedCatalogProducts();
  if (catalog.length === 0) {
    console.error("No catalog products found — seed catalog first.");
    process.exit(1);
  }

  let reviews = 0;

  for (const product of catalog) {
    const reviewCount = deterministicReviewCount(
      product.slug,
      REVIEWS_MIN_PER_PRODUCT,
      REVIEWS_MAX_PER_PRODUCT,
    );
    const picked = deterministicShuffle(REVIEWER_POOL, product.slug).slice(0, reviewCount);
    const variantBase = deterministicReviewerOffset(product.slug);

    for (let i = 0; i < reviewCount; i++) {
      const profile = picked[i]!;
      const locale = REVIEW_SEED_LOCALES[i % REVIEW_SEED_LOCALES.length]!;
      const body = seedReviewBody(locale, {
        name: product.name,
        movement: getProductMovement(product),
        profile:
          product.storefrontSubcategory?.trim().toLowerCase() === "ultra-thin"
            ? "ultra-thin"
            : null,
        categoryLabel: product.categoryLabel,
      }, i + variantBase);

      const email = `seed-${product.slug}-${i}@${SEED_EMAIL_HOST}`;

      const user = await prisma.user.create({
        data: {
          name: displayName(profile),
          firstName: profile.firstName,
          lastName: profile.lastName,
          displayName: displayName(profile),
          email,
          image: null,
        },
      });

      await prisma.productReview.create({
        data: {
          userId: user.id,
          orderId: randomUUID(),
          productSlug: product.slug,
          rating: 5,
          body,
          imageUrlsJson: "[]",
          status: "approved",
          createdAt: deterministicReviewDate(product.slug, i),
        },
      });
      reviews++;
    }

    console.log(`  ${product.slug}: ${reviewCount} reviews (mixed locales)`);
  }

  console.log(
    `Done. ${reviews} five-star reviews across ${catalog.length} product(s) (${REVIEWS_MIN_PER_PRODUCT}–${REVIEWS_MAX_PER_PRODUCT} each).`,
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
